<script setup lang="ts">
import { computed } from "vue";
import type { PDFReport } from "@/types";
import { toast } from "@/composables/useToast";
import { formatRupiah, formatDate } from "@/utils/formatHelper";
import jsPDF from "jspdf";

interface Props {
  reports: PDFReport[];
}

const props = defineProps<Props>();

// Sort reports
const sortedReports = computed(() => {
  return [...props.reports].sort((a, b) => new Date(b.tanggal).getTime() - new Date(a.tanggal).getTime());
});

// Handle PDF download
const handleDownload = (report: PDFReport) => {
  try {
    const pageSize = report.pageSize.toLowerCase() as "a4" | "a5" | "letter";
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: pageSize,
    });

    // Set font
    pdf.setFont("helvetica");

    // Add title
    pdf.setFontSize(20);
    pdf.setFont("helvetica", "bold");
    pdf.text(report.judul, 20, 20);

    // Add page size info
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Ukuran: ${report.pageSize}`, 20, 30);

    // Add date
    pdf.text(`Tanggal: ${formatDate(report.tanggal)}`, 20, 36);

    // Add separator line
    pdf.setLineWidth(0.5);
    pdf.line(20, 40, pdf.internal.pageSize.getWidth() - 20, 40);

    // Add description/content
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text("Deskripsi:", 20, 50);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);

    // Split text into lines to fit page width
    const maxWidth = pdf.internal.pageSize.getWidth() - 40;
    const lines = pdf.splitTextToSize(report.deskripsi, maxWidth);
    pdf.text(lines, 20, 58);

    // Calculate Y position for nominal
    const descriptionHeight = lines.length * 6;
    const nominalY = 58 + descriptionHeight + 10;

    // Add nominal
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text("Nominal:", 20, nominalY);

    pdf.setFontSize(14);
    pdf.setTextColor(0, 100, 0); // Green color
    pdf.text(formatRupiah(report.nominal), 20, nominalY + 8);

    pdf.setTextColor(0, 0, 0);

    // Add footer
    const pageHeight = pdf.internal.pageSize.getHeight();
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "italic");
    pdf.text("Generated by PDF Report Generator", 20, pageHeight - 10);

    // Save PDF
    pdf.save(`${report.judul.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`);

    toast.success("Berhasil!", {
      description: `PDF "${report.judul}" berhasil diunduh`,
    });
  } catch (error) {
    console.error("Error generating PDF:", error);
    toast.error("Gagal!", {
      description: "Terjadi kesalahan saat mengunduh PDF",
    });
  }
};
</script>

<template>
  <div class="bg-white rounded-lg shadow">
    <div class="px-6 py-4 border-b border-gray-200">
      <h2 class="text-xl font-bold text-gray-800">Daftar Laporan PDF</h2>
      <p class="text-gray-600 text-sm mt-1">Total: {{ reports.length }} laporan</p>
    </div>

    <div v-if="reports.length === 0" class="px-6 py-12 text-center">
      <div class="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gray-100 mb-4">
        <i class="bi bi-inbox text-3xl text-gray-400"></i>
      </div>
      <h3 class="text-lg font-semibold text-gray-700 mb-2">Belum Ada Data</h3>
      <p class="text-gray-500">Silakan generate PDF terlebih dahulu menggunakan form di atas</p>
    </div>

    <div v-else class="overflow-x-auto">
      <table class="w-full">
        <thead>
          <tr>
            <th>No</th>
            <th>Judul</th>
            <th>Page Size</th>
            <th>Nominal</th>
            <th>Tanggal</th>
            <th>Aksi</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(report, index) in sortedReports" :key="report.id" :class="['transition-colors', index % 2 === 0 ? 'bg-white hover:bg-gray-50' : 'bg-gray-50 hover:bg-gray-100']">
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
              {{ index + 1 }}
            </td>
            <td class="px-6 py-4 text-sm text-gray-900">
              <div class="font-medium">{{ report.judul }}</div>
              <div class="text-gray-500 text-xs mt-1 line-clamp-2">{{ report.deskripsi }}</div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
              <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                {{ report.pageSize }}
              </span>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
              {{ formatRupiah(report.nominal) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              {{ formatDate(report.tanggal) }}
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm">
              <button @click="handleDownload(report)" class="inline-flex items-center gap-2 px-3 py-1.5 bg-green-600 hover:bg-green-700 text-white rounded-md shadow-sm cursor-pointer" title="Download PDF">
                <i class="bi bi-download"></i>
                <span class="hidden sm:inline">Download</span>
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<style scoped>
thead {
  background: #f9fafb;
  border-bottom: 1px solid #e5e7eb;
}

th {
  padding: 12px 24px;
  text-align: left;
  font-size: 12px;
  font-weight: 600;
  color: #374151;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
